### ISSUE TITLE
subdependencies are not handled

### ISSUE THREAD

**Issue by bruceauyeung** [FormidableLabs/babel-plugin-replace-require#5]
given that:
1. file a.js requires b.js
2. b.js requires c.js

file b will not be handled by this plugin, am I right ? if so, how can let this plugin to handle subdependencies and so on ?

**Comment by ryan-roemer** [comment]
This plugin literally rewrites patterns in require/import statements when parsing the AST. It is agnostic as to what later happens with actual imports at build or runtime.

If there’s a use case you see that it should support but doesn’t given those constraints please create a minimal repository with install and build instructions as well as what you would like to see happening in the Babel output that isn’t and the we can dive in and potentially help more. Thanks!

**Comment by bruceauyeung** [comment]
closing because this behavior looks to be intended.
